services:
  # Aplicativo Web
  frontend:
    container_name: bookhere_webapp
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - frontend-network
  
  # API
  backend:
    container_name: bookhere_api
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network
  
  # banco de dados PostgreSQL
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db_data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge